### ISSUE TITLE
Error with Test-LMAppliesToQuery

### ISSUE THREAD

**Issue by AUrhino** [logicmonitor/lm-powershell-module#14]
When testing Test-LMAppliesToQuery with the example (or any query) you get an error.

Test-LMAppliesToQuery -Query "system.hostname == 'server01'"
Failed to execute web request(400): Lexical error at line 1, column 20.  Encountered: "\'" (39), after : ""

**Comment by stevevillardi** [comment]
I believe appliesTo queries need to contain double quotes and not single quotes. Can you try writing your query like this:

`Test-LMAppliesToQuery -Query 'system.hostname == "server01"'`

**Comment by stevevillardi** [comment]
Trying your query in my portal gets the same expected lexical error:
![image](https://github.com/user-attachments/assets/a029ad8c-94d7-42d8-a7bb-54fb8ebaa575)

Vs doing it with double quotes:
![image](https://github.com/user-attachments/assets/40d94cc1-03cf-4322-90a7-3035c2b35ea1)

**Comment by stevevillardi** [comment]
you could also use double quotes in the event you need to use a variable within the string but youll need to escape the double quotes in those situations.
