### ISSUE TITLE
Set-LMDeviceDatasourceInstance does not allow updates. Will replace

### ISSUE THREAD

**Issue by AUrhino** [logicmonitor/lm-powershell-module#15]
In this example:
#Get device details by hostname value
$Device = Get-LMDevice -Name "192.168.1.4"

#Pull datasource and instance details
$DataSource = Get-LMDeviceDatasourceList -id $Device.id | Where-Object {$_.dataSourceName -eq "SNMP_Network_Interfaces"}
$Instances = Get-LMDeviceDatasourceInstance -DatasourceId $Datasource.datasourceId -DeviceId $Device.id

#Find instance needing to be updated
$eth0 = $Instances | Where-Object {$_.name -like "*eth0*"}

#Update instance with required props
Set-LMDeviceDatasourceInstance -DeviceId $Device.id -DatasourceId $DataSource.datasourceid -InstanceId $eth0.id -Properties @{"out_speed"=25;"in_speed"=500}

If you have an existing property, this will replace with the 2 in the property hash.
Would be good if this has a option of -PropertiesMethod

**Comment by stevevillardi** [comment]
Thanks for the report, I can took a look at the exiting Set-LMx cmdlets and make sure the -PropertiesMethod is added in the next release.
