### ISSUE TITLE
Support for NetScan policy schedule (New-LMNetScan and Set-LMNetScan)

### ISSUE THREAD

**Issue by eemil** [logicmonitor/lm-powershell-module#20]
It would be nice if these cmdlets would support a schedule other than the current hardcoded one ("manual").

**Comment by stevevillardi** [comment]
we can certainly add support for a PSCustomObject parameter that reflects the expected Schedule schema for a netscan.

**Comment by eemil** [comment]
Thanks, I downloaded the new release and it's working just fine!
```powershell
PS C:\Users\x> $schedule = [pscustomobject]@{cron = "33 * * * *"; notify = $false; recipients = @(); type = "hourly"; timezone = "Etc/UTC" }
PS C:\Users\x> New-LMNetScan -name testing -CollectorId 1 -Description testing -Schedule $schedule -SubnetRange 10.10.10.10
```
p.s. to anyone googling `Schedule object is missing required property: notify`, your $schedule is probably a hashtable and needs to be cast as a pscustomobject to work with -Schedule.

**Comment by stevevillardi** [comment]
Thanks for the follow up confirmation on it working in the latest release! @eemil Appreciate the feedback!
