### ISSUE TITLE
Get-LMDeviceDatasourceInstanceAlertSetting breaks for instance names containing square brackets

### ISSUE THREAD

**Issue by summors** [logicmonitor/lm-powershell-module#5]
This block (lines 51-64) uses a "-like" comparison, which seems to break when the instance name characters that operator treats as special (e.g., the square brackets in interfaces discovered by the SNMP_Network_Interfaces datasource - _SNMP_Network_Interfaces-GigabitEthernet/1/0/48 [ID:56]_."

```
        If ($DatasourceName) {
            $LookupResult = (Get-LMDeviceDatasourceInstance -DatasourceName $DatasourceName -DeviceId $Id | Where-Object { $_.name -like "*$InstanceName"}).Id
            If (Test-LookupResult -Result $LookupResult -LookupString $InstanceName) {
                return
            }
            $HdsiId = $LookupResult
        }
        Else{
            $LookupResult = (Get-LMDeviceDatasourceInstance -DatasourceId $DatasourceId -DeviceId $Id | Where-Object { $_.name -like "*$InstanceName"}).Id
            If (Test-LookupResult -Result $LookupResult -LookupString $InstanceName) {
                return
            }
            $HdsiId = $LookupResult
        }
```

I haven't tested exhaustively and I'm probably missing a more elegant fix, but adding a -eq comparison seems to make the function behave according to its intent. Resulting file attached.
[Get-LMDeviceDatasourceInstanceAlertSetting.txt](https://github.com/user-attachments/files/15593536/Get-LMDeviceDatasourceInstanceAlertSetting.txt)

**Comment by stevevillardi** [comment]
Thanks for the report. Let me take a look at some possible solutions for this. The lookup functionality can certainly be improved overall and might be a good time to revisit it.
